
title: Hugo Storm
description: Cybersecurity professional sharing expertise and insights
url: https://stormhugo.github.io
baseurl: ""
author: Hugo Storm


theme: minima
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
sass:
  sass_dir: assets/css
  style: compressed


collections:
  certifications:
    output: true
  pages:
    output: true
    permalink: /:path/


header_pages:
  - index.md
  - blog.md
  - contact.md


social:
  github: stormhugo
  linkedin: stormhugo
  email: hello@hello.com


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - README.md
  - LICENSE


include:
  - categories.html


paginate: 5
paginate_path: "/blog/page:num/"
