# Site settings
title: Hugo Storm
description: Cybersecurity professional sharing expertise and insights
url: https://stormhugo.github.io
baseurl: ""
author: Hugo Storm

# Build settings
theme: minima
markdown: kramdown
permalink: /blog/:title/
sass:
  sass_dir: assets/css
  style: compressed

# Collections
collections:
  certifications:
    output: true

# Navigation links
header_pages:
  - index.md
  - blog.md
  - contact.md

# Social media profiles
social:
  github: username
  linkedin: username
  email: hello@example.com

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - README.md
  - LICENSE